version: '2'
services:
  nginx:
    image: nginx:1.11.10-alpine
    ports:
      - 3000:80
    volumes:
      - ./docker/nginx/config/nginx.app.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
  web:
    build: ./docker/php/
    ports:
      - 9000:9000
    volumes:
      - .:/app
      - /app/vendor
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://www@postgres/test
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: www
      POSTGRES_DB: test